### ISSUE TITLE
pia -a KeyError: 'Cipher'

### ISSUE THREAD

**Issue by averagejoey2000** [flamusdiu/python-pia#25]
I needed to change my VPN hosts to include CA_Toronto so I could port forward on my arch linux machine, but when I changed my pia.conf and used the tool, I got the following output:

```
sudo pia -a
[sudo] password for averagejoey2000:
Traceback (most recent call last):
  File "/usr/bin/pia", line 11, in <module>
    load_entry_point('pia==3.3b0', 'console_scripts', 'pia')()
  File "/usr/lib/python3.5/site-packages/pia/command_line.py", line 23, in main
    pia.run.run()
  File "/usr/lib/python3.5/site-packages/pia/run.py", line 53, in run
    properties.parse_conf_file()
  File "/usr/lib/python3.5/site-packages/pia/conf/properties.py", line 271, in parse_conf_file
    props.port = getattr(configure_section, "port", [props.default_port])[0]
  File "/usr/lib/python3.5/site-packages/pia/conf/properties.py", line 160, in port
    self._cipher = config['cipher']
KeyError: 'cipher'
```

/etc/private-internet-access/pia.conf

```
[pia]
openvpn_auto_login = True

[configure]
apps = openvpn,nm
hosts = CA Toronto, Japan, UK London, US California, US Chicago, US East, US Seattle, US Silicon Valley
port = 1198
```

Tried using dev branch and master branch, neither works.

**Comment by flamusdiu** [comment]
Umm, okay, I'll see what happened
