### ISSUE TITLE
Missing hosts file

### ISSUE THREAD

**Issue by chrisspen** [flamusdiu/python-pia#31]
Attempting to run `pia --help` throws the error:

    Traceback (most recent call last):
      File "/myproject/.env/bin/pia", line 11, in <module>
        load_entry_point('pia==3.3.2', 'console_scripts', 'pia')()
      File "/myproject/.env/lib/python3.5/site-packages/pkg_resources/__init__.py", line 561, in load_entry_point
        return get_distribution(dist).load_entry_point(group, name)
      File "/myproject/.env/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2649, in load_entry_point
        return ep.load()
      File "/myproject/.env/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2303, in load
        return self.resolve()
      File "/myproject/.env/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2309, in resolve
        module = __import__(self.module_name, fromlist=['__name__'], level=0)
      File "<frozen importlib._bootstrap>", line 969, in _find_and_load
      File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
      File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
      File "/myproject/.env/lib/python3.5/site-packages/pia-3.3.2-py3.5.egg/pia/__init__.py", line 21, in <module>
      File "<frozen importlib._bootstrap>", line 969, in _find_and_load
      File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
      File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
      File "/myproject/.env/lib/python3.5/site-packages/pia-3.3.2-py3.5.egg/pia/utils/__init__.py", line 1, in <module>
      File "<frozen importlib._bootstrap>", line 969, in _find_and_load
      File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
      File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
      File "/myproject/.env/lib/python3.5/site-packages/pia-3.3.2-py3.5.egg/pia/utils/log.py", line 21, in <module>
      File "<frozen importlib._bootstrap>", line 969, in _find_and_load
      File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
      File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
      File "/myproject/.env/lib/python3.5/site-packages/pia-3.3.2-py3.5.egg/pia/conf/__init__.py", line 19, in <module>
      File "<frozen importlib._bootstrap>", line 969, in _find_and_load
      File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
      File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
      File "/myproject/.env/lib/python3.5/site-packages/pia-3.3.2-py3.5.egg/pia/conf/properties.py", line 293, in <module>
      File "/myproject/.env/lib/python3.5/site-packages/pia-3.3.2-py3.5.egg/pia/conf/properties.py", line 116, in __init__
      File "/myproject/.env/lib/python3.5/site-packages/pia-3.3.2-py3.5.egg/pia/conf/properties.py", line 283, in get_default_hosts_list
    FileNotFoundError: [Errno 2] No such file or directory: '/etc/private-internet-access/vpn-hosts.txt'

Where do I find or how do I generate this file?

I have PIA's OpenVPN script installed, and use it through Network Manager's OpenVPN plugging, which lists all the VPN hosts.

**Comment by flamusdiu** [comment]
That's odd .. the `vpn-hosts.txt` is generated when it's installed. not sure why you would be missing it.

**Comment by flamusdiu** [comment]
Did you just clone the GigHub and try to do the install through `pip`?

**Comment by chrisspen** [comment]
I cloned it and then installed it using `python setup.py install` from within my virtualenv.

**Comment by flamusdiu** [comment]
Yup, that's why you are missing that file. It's created from the AUR PKGBUILD. You would also be missing the certification files. I would need to do some rework to get those installed from the pip install.

**Comment by flamusdiu** [comment]
Closing issue if there is still a problem, please reopen.
